### ISSUE TITLE
clarity to 03

### ISSUE THREAD

**Issue by anoronh4** [pybites/challenges#789]
instructions for challenge 03 were a bit unclear to me. for example we are instructed to extract "tags" but the help solution says to extract something like `imatag` from `'<category>imatag</category>'`. In an html context that's not what i understand a "tag" to be, and it's not clear that it needs to come specifically from the `<category>` tag. it's also not clear why i'm given two input files, `tag.html` and `rss.xml`. "Similarity" between words is also not clearly defined in the prompt.

**Comment by GeoffRiley** [comment]
The instructions do state that the task is looking at RSS tags and gives a few examples of the tags that are being the subject of the effort.  Personally I do not feel that there is a confusion in the challenge because there is no point in the instructions that use the term `tags` in any way other than referring to the RSS tags.

The standard definition of an `rss.xml` file is widely available online, a simple web search will quickly reveal multiple sources, for example [the RSS 2.0 Specification](https://www.rssboard.org/rss-specification). 

I think that it would be safe to expect someone taking this kind of challenge to chase down the specifications of whatever is being worked upon, and that even a cursory comparison of the examples with the actual provided feed sample would reveal that the RSS tags are held in the `<category>…</category>` xml constructs.  The challenge is not framed in an html context, so what you understand a tag to be in that context is not really relevant.

Lastly, examples are provided of what __similarity__ means, and even an example of something that should _not_ be considered similar is shown.

Remember that these are supposed to be _challenges_, it would be too easy if everything was completely spelt out: half of the 'fun' is getting to grips with the meaning of the question.

**Comment by bbelderbos** [comment]
Thanks @GeoffRiley, leaving this unaddressed for now.
